### ISSUE TITLE
Feature: html

### ISSUE THREAD

**Issue by fagcinsk** [apseren/ap37#6]
Will be so cool, if layout can be implemented by html. So, less code, more control.

**Comment by apseren** [comment]
I considered doing that when I first implemented it. But I wanted to make it console like and not a WebView launcher. And because of that, an Android Bitmap with Canvas.drawText calls seems a better solution. If html will ever be supported will probably be as a separated launcher. It is a good idea to anyone who is looking for a new project and wants to go ahead and implement a launcher like that.
